FROM python:3.12-slim

# Установка зависимостей
RUN apt-get update && apt-get install -y cron

# Рабочая директория
WORKDIR /app

# Копирование файлов
COPY . .

# Установка Python-зависимостей
RUN pip install --no-cache-dir -r requirements.txt

# Настройка cron
RUN echo "0 3 * * * /bin/bash /app/scripts/update_messages.sh" >> /etc/cron.d/motiv-bot
RUN chmod 0644 /etc/cron.d/motiv-bot
RUN crontab /etc/cron.d/motiv-bot

# Запуск
CMD ["sh", "-c", "cron && python bots/motiv_bot.py"]