FROM python:3.12-slim

# Установка зависимостей
RUN apt-get update && apt-get install -y cron

# Рабочая директория
WORKDIR /app

# Копирование файлов
COPY . .

# Установка Python-зависимостей
RUN pip install --no-cache-dir -r requirements.txt
